stages:
  - test
  - review
  - build
  - release

include:
  - template: Code-Quality.gitlab-ci.yml
  - 'https://gitlab.avisi.cloud/ame/ci/raw/master/.templates/danger.yaml'
  - 'https://gitlab.avisi.cloud/ame/ci/raw/master/.templates/golang.yaml'
  - 'https://gitlab.avisi.cloud/ame/ci/raw/master/.templates/sonar-qube.yaml'

variables:
  BRANCH: $CI_COMMIT_BRANCH
  COMMIT: $CI_COMMIT_SHA
  VERSION: $CI_COMMIT_TAG

go:test:
  extends: .go:test
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - go mod download
  cache:
    paths:
      - .go/pkg/mod/
  stage: test

sonar:scanner:
  extends: .sonar:scanner
  stage: test
  only: [master,tags]
  allow_failure: true

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]
  tags: [docker]

go:code_review:
  stage: review
  extends: .go:code_review

code_navigation:
  extends: .go:code_navigation
  stage: build
  needs: []

go:build:
  extends: .go:make:build
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    policy: pull
    paths:
      - .go/pkg/mod/
  stage: build
  before_script:
    - mkdir -p .go
    - go mod download
  script:
    - make linux
    - make darwin
  artifacts:
    paths:
      - bin/acloud-toolkit-linux-amd64
      - bin/acloud-toolkit-darwin-amd64

release:
  stage: release
  image:
    name: goreleaser/goreleaser:v0.182.1
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GORELEASER_CURRENT_TAG: ${CI_COMMIT_TAG}
  script:
    - goreleaser release --rm-dist
  dependencies: []
