# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: "acloud-toolkit"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

before:
  hooks:
    - go mod tidy
    - ./scripts/shell-completions.sh

archives:
  - files:
      - completions/*

homebrew_casks:
  - repository:
      owner: avisi-cloud
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TOOLS_GITHUB_TOKEN }}"
    homepage: "https://docs.avisi.cloud/docs/cli/acloud-toolkit/overview"
    conflicts:
      - formula: "acloud-toolkit"
    completions:
      bash: completions/acloud-toolkit.bash
      zsh: completions/acloud-toolkit.zsh
      fish: completions/acloud-toolkit.fish

release:
  footer: |
    **Full Changelog**: https://github.com/avisi-cloud/acloud-toolkit/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github
  sort: asc
  groups:
    - title: "Breaking changes"
      regexp: '^.*?\w+(\(.+\))?!:\s?.+$'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 3
    - title: "Others"
      order: 999
  filters:
    # Commit messages matching the regexp listed here will be removed from the changelog
    exclude:
      - '^Merge branch'
      - '^.*?(test|style)(\(.+\))??!?:.+$'
      - 'initial commit'
