# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: "acloud-toolkit"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

before:
  hooks:
    - go mod tidy
    - ./scripts/shell-completions.sh

archives:
  - files:
      - completions/*

homebrew_casks:
  - repository:
      owner: avisi-cloud
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TOOLS_GITHUB_TOKEN }}"
    homepage: "https://docs.avisi.cloud/docs/cli/acloud-toolkit/overview"
    completions:
      bash: completions/acloud-toolkit.bash
      zsh: completions/acloud-toolkit.zsh
      fish: completions/acloud-toolkit.fish
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            # replace 'acloud-toolkit' with the actual binary name
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acloud-toolkit"]
          end

release:
  footer: |
    **Full Changelog**: https://github.com/avisi-cloud/acloud-toolkit/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github
  sort: asc
  groups:
    - title: "Breaking changes"
      regexp: '^.*?\w+(\(.+\))?!:\s?.+$'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 3
    - title: "Others"
      order: 999
  filters:
    # Commit messages matching the regexp listed here will be removed from the changelog
    exclude:
      - '^Merge branch'
      - '^.*?(test|style)(\(.+\))??!?:.+$'
      - 'initial commit'
