name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Homebrew PAT
        run: |
          curl -f \
            -H "Authorization: token ${{ secrets.HOMEBREW_TOOLS_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/homebrew-tools
        env:
          HOMEBREW_TOOLS_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOOLS_GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOOLS_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOOLS_GITHUB_TOKEN }}
